
mqtt:
  # Enable/disable mqtt transport protocol.
  enabled: true
  bind_address: 0.0.0.0
  bind_port: 1883
  adaptor: JsonMqttAdaptor
  timeout: 10000
  netty:
    leak_detector_level: DISABLED
    boss_group_thread_count: 1
    worker_group_thread_count: 8
    max_payload_size: 65536
    so_keep_alive: false

# CoAP server parameters
coap:
  # Enable/disable coap transport protocol.
  enabled: true
  bind_address: 0.0.0.0
  bind_port: 5683
  adaptor: JsonCoapAdaptor
  timeout: 10000

# datasource info
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/famas?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

# mybatis configuration
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.grozacloud.famas.dao
